Flask/current/blueprintapp/todos/models.py
from blueprintapp.app import db

class Todo(db.Model):

    __tablename__ = 'todos'

    tid = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    description = db.Column(db.String)
    done = db.Coulmn(db.Boolean, nullable = False)

    def __repr__(self):
        return f"{self.description}, Done: {self.done}"
    
    def get_id(self):
        return self.tid
    

Flask/current/blueprintapp/todos/routes.py
from flask import redirect, request, render_template, url_for, Blueprint

from blueprintapp.app import db

from blueprintapp.todos.models import Todos

todos = Blueprint('todos', __name__ , template_folder='templates')

@todos.route('/')
def index():
    todos = Todos.query.all()
    return render_template('todos/index.html', todos = todos)

@todos.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('todos/create.html')
    
    elif request.method == 'POST':
        title = request.form.get('Title')
        description = request.form.get('Description')
        done = True if 'Done' in request.form.keys() else False

        description = description if description != '' else None

        todo = Todos(Title = title, Description= description, Done = done)

        db.session.add(todo)
        db.session.commit()

        return redirect(url_for('todos.index'))

Flask/current/blueprintapp/todos/templates/todos/create.html
{ % extends 'base.html' %}

{% block title %}CREATE PAGE{% endblock %}

{% block content %}
<h1>CREATE TODO</h1>
<form action="{{url_for('todos.create')}}" method="POST">
    <input type="text" name="Title" placeholder="Title" required="required">
    <input type="text" name="Description" placeholder="description" >
    <input type="checkbox" name="Done" required="required">
    <input type="submit" name="ADD to TODO">

</form>


{% endblock %}

Flask/current/blueprintapp/todos/templates/todos/index.html
{ % extends 'base.html' %}

{% block title %}TODOS{% endblock %}

{% block content %}
<ul>
    {% for todo in todos %}
    <li>todo</li>
    {% endfor %}
</ul>

{% endblock %}